### ISSUE TITLE
Other cities 

### ISSUE THREAD

**Issue by gedw99** [stv0g/cfac#4]
This is really interesting . I live in berlin and there are probably similar sources worth scraping for Berlin .

mid there a backend system for reusing all the data scraped with sone sort of cave invalidation so the higher level systems sing the data can see when it changes via drag headers or similar ? 

The idea of modelling a city based on its digital flow is really cool for car battery vehicle to grid systems which I think your also interested in .

fewl free to touch base on telegram if you want . See my profile

**Comment by stv0g** [comment]
Yes, I am definitely open to add support other cities :) We can also adjust the directory structure to keep the local data-sources within their sub-dir. Actually some of the data sources are not limited to Aachen (McFit, Highway cameras, Cambio, LANUV, ...).

> mid there a backend system for reusing all the data scraped with sone sort of cave invalidation so the higher level systems sing the data can see when it changes via drag headers or similar ?

Thats still an open question for me. There is a legal side to this, that providing the data via common backend would be difficult as not all data sources provided open-data and I would walk on quite thin ice offering data I dont actually own.

From the technical perspective, I did not want to invent yet another Smart-city API to provide a common interface.
However there are some standardized APIs like [SensorThings](https://www.ogc.org/standards/sensorthings) which could maybe be the way to go here?

**Comment by stv0g** [comment]
I will close the issue due to inactivity. Please feel free to contact me via Twitter (@stv0g) or mail (post@steffenvogel.de) to continue the discussion.
